# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [20]:
import pandas as pd

#URLs de los archivos CSV
url1 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
url2 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv"
url3 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv"

#cargo los archivos en dataframes
df1 = pd.read_csv(url1)
df2 = pd.read_csv(url2)
df3 = pd.read_csv(url3)

In [21]:
#concateno los tres dataframes en uno solo
data = pd.concat([df1, df2, df3], ignore_index=True)

In [22]:
#limpio nombres de columnas, en minusculas y espacios por _
data.columns = (data.columns.str.strip().str.lower().str.replace(" ", "_"))

In [23]:
#elimino filas duplicadas
data = data.drop_duplicates()

In [24]:
#identifico numero de valores nulos
null_counts = data.isnull().sum()
null_counts

customer                        1
st                           7071
gender                       7193
education                       1
customer_lifetime_value         8
income                          1
monthly_premium_auto            1
number_of_open_complaints       1
policy_type                     1
vehicle_class                   1
total_claim_amount              1
state                        2065
gender                       2065
dtype: int64

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [25]:
# URL del archivo CSV
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv"

#cargo el archivo en un dataframe
df = pd.read_csv(url)

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

In [26]:
#redondeo ingresos totales a 2 decimales
df['total_claim_amount'] = df['total_claim_amount'].round(2)

In [27]:
df["total_claim_amount"]

0         292.80
1         744.92
2         480.00
3         484.01
4         707.93
          ...
10905    1214.40
10906     273.02
10907     381.31
10908     618.29
10909    1021.72
Name: total_claim_amount, Length: 10910, dtype: float64

In [28]:
#creo tabla que muestre los ingresos totales por canal de ventas
pivot_sales = df.pivot_table(values='total_claim_amount', index='sales_channel', aggfunc='sum').round(2)

In [29]:
pivot_sales

               total_claim_amount
sales_channel
Agent                  1810226.88
Branch                 1301204.34
Call Center             926601.02
Web                     706600.02

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

In [30]:
#creo tabla que muestre el valor medio de vida del cliente por género y educación
pivot_ltv = df.pivot_table(values='customer_lifetime_value', index='gender', columns='education', aggfunc='mean').round(2)

In [31]:
pivot_ltv

education  Bachelor  College   Doctor  High School or Below   Master
gender
F           7874.27  7748.82  7328.51               8675.22  8157.05
M           7703.60  8052.46  7415.33               8149.69  8168.83

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [32]:
# Your code goes here